title: Ry Cutter # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A PhD in Astrophysics turned Data Scientist and software engineer, driven by a passion for science communication and innovative problem-solving. 
  <br><br>
  <b>Multidisciplinary:</b><br>
  - Lead Innovation Data Scientist <br>
  - Customer Insights and Behaivour Analyst <br>
  - Quantitative Financial Analyst <br>
  - Machine Learning Engineer <br>
  <br><br>
  Machine Learning, Embedded ML, Software/Firmware Engineering, Automation, Python, Time Series, Forecasting, NLP, Data Visualisation, Experimental Design, Physics, Statistics, Wearable Tech, Connectivity
  <br><br>
  <a href="https://uk.linkedin.com/in/ry-cutter">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
